
cc_library(
  name = "transpiler",
  hdrs = ["transpiler.h"],
  srcs = [
    "transpiler.cc",
  ],
  deps = [
    "@spirv_tools//:spirv_tools",
    "@spirv_headers//:spirv_cpp_headers",
    "@spirv_headers//:spirv_common_headers",
  ]
)
